import os

# Forçar o uso de g++ ao invés de cl.exe (MSVC)
env = Environment(CC='g++', CXX='g++')

# Caminho correto para os headers e a lib que você compilou
godot_headers_path = os.path.join("..", "..", "cpp", "godot-cpp-4.4", "include")
godot_cpp_path = os.path.join("..", "..", "cpp", "godot-cpp-4.4")

# Incluir os paths nos flags de compilação
env.Append(CPPPATH=[godot_headers_path, godot_cpp_path])
env.Append(LIBPATH=[godot_cpp_path])

# Fontes do seu módulo
sources = Glob("src/*.cpp")

# Nome da lib final
target_name = "libexample"

# Gera o static library
target = env.StaticLibrary(target_name, sources)

Default(target)
