import os

platform = ARGUMENTS.get('platform', '')
env = Environment()

root = os.path.join('..', '..', 'godot-cpp')

env.Append(CPPPATH=[
    os.path.join(root, 'include'),
    os.path.join(root, 'include', 'godot_cpp'),
    os.path.join(root, 'include', 'godot_cpp', 'classes'),
    os.path.join(root, 'core'),
    os.path.join(root, 'variant'),
    os.path.join(root, 'templates'),
    os.path.join(root, 'gdextension'),
])

env.Append(LIBPATH=[os.path.join(root, 'bin')])
env.Append(LIBS=['godot-cpp'])

sources = ['register_types.cpp'] + Glob('src/*.cpp')

suffix = '.so'
if platform == 'windows':
    suffix = '.dll'
elif platform == 'macos':
    suffix = '.dylib'

env['SHLIBSUFFIX'] = suffix

os.makedirs('bin', exist_ok=True)
lib = env.SharedLibrary('bin/example', sources)

Default(lib)
