import os

env = Environment(tools=['default', 'msvc'], CC='cl', CXX='cl')

# Caminhos dos headers do Godot C++
godot_headers_path = os.path.join("..", "..", "..", "godot-cpp", "include")
godot_cpp_path = os.path.join("..", "..", "..", "godot-cpp")

# Incluindo todos os caminhos necessários
env.Append(CPPPATH=[
    godot_headers_path,
    godot_cpp_path,
    os.path.join(godot_headers_path, "godot_cpp")
])

# Incluindo caminho para as libs
env.Append(LIBPATH=[godot_cpp_path])

# Fontes do módulo
sources = Glob("src/*.cpp")

# Nome da lib final
target_name = "libexample"

# Geração da static library
target = env.StaticLibrary(target_name, sources)

Default(target)
